name: Make Package

on:
  workflow_dispatch:

jobs:
  build:

    env:
      PROJECT: StereoKit.csproj
      
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: '2.7.5'
    - name: Restore dependencies
      run: dotnet restore $PROJECT
    - name: Pack
      run: dotnet pack --configuration Release $PROJECT
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
